export const TEMPLATE_SELECTED = "TEMPLATE_SELECTED";

export const PERSONAL_SUBMIT = "PERSONAL_SUBMIT";

export const EDUCATION_SUBMIT = "EDUCATION_SUBMIT";


export const EXPERIENCE_SUBMIT = "EXPERIENCE_SUBMIT";


export const SKILLS_SUBMIT = "SKILLS_SUBMIT";
